### ISSUE TITLE
Failed to load the autocomplete-erlang package

### ISSUE THREAD

**Issue by hunnapikes** [iraasta/autocomplete-erlang#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.188.0
**System**: linux 3.13.0-48-generic
**Thrown From**: [autocomplete-erlang](https://github.com/iraasta/autocomplete-erlang) package, v0.1.0
### Stack Trace

Failed to load the autocomplete-erlang package

```
At Cannot find module 'pty.js'

Error: Cannot find module 'pty.js'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/serejk3/.atom/packages/autocomplete-erlang/lib/server/erlang/erlang.js:6:11)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/serejk3/.atom/packages/autocomplete-erlang/lib/server/static.js:30:1)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/serejk3/.atom/packages/autocomplete-erlang/lib/autocomplete-erlang.coffee:2:1)
  at Object.<anonymous> (/home/serejk3/.atom/packages/autocomplete-erlang/lib/autocomplete-erlang.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:678:34)
  at /usr/share/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:460:30)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```
### Commands

```
  2x -6:47.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
  4x -6:46.1 window:increase-font-size (atom-text-editor.editor.is-focused)
  2x -6:42.2 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
  4x -6:41.8 core:backspace (atom-text-editor.editor.is-focused)
     -6:38.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -6:37.8 core:select-all (atom-text-editor.editor.is-focused)
     -6:23.2 core:confirm (atom-text-editor.editor.mini)
  4x -0:57.9 core:backspace (atom-text-editor.editor.mini)
     -0:52.0 core:confirm (atom-text-editor.editor.mini)
     -0:23.2 core:save (atom-text-editor.editor.is-focused)
  4x -0:09.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.7 core:save (atom-text-editor.editor.is-focused)
  3x -0:04.6 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:00.3 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-erlang, v0.1.0
go-plus, v3.3.1
language-erlang, v2.0.0

# Dev
No dev packages
```

**Comment by wende** [comment]
This has been an error with pty.js being submodule.
No idea what was the cause
Emmbedding the directory instead of adding it to node_modules fixed the bug

**Comment by Bleakwise** [comment]
Embedding the directory?

**Comment by wende** [comment]
Yes. I've had to add module manually instead of dependency in package.json.
Updated it should work. 
But I'll be changing the whole package soon. The same way I've modified autocomplete-elixir

**Comment by Bleakwise** [comment]
So I should just google something like "manually add github atom plugin package" ?

**Comment by Bleakwise** [comment]
I came up with this, sound about right?
https://discuss.atom.io/t/manually-install-package/9251

**Comment by wende** [comment]
No no. There is no need for that. I had to do that.

**Comment by wende** [comment]
I've changed the entire system. Check out v1.0.0
73e1a32c9af8b4cc63c16b04013616f0c61c0c8e
