### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdout' of undefined

### ISSUE THREAD

**Issue by 1ahshqa** [iraasta/autocomplete-erlang#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-erlang](https://github.com/iraasta/autocomplete-erlang) package, v1.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'stdout' of undefined

```
At /C:/Users/90618/.atom/packages/autocomplete-erlang/lib/alchemide/wrapper.coffee:52

TypeError: Cannot read property 'stdout' of undefined
  at Object.exports.init (C:\Users\90618\.atom\packages\autocomplete-erlang\lib\alchemide\wrapper.coffee:34:19)
  at exit (C:\Users\90618\.atom\packages\autocomplete-erlang\lib\alchemide\wrapper.coffee:21:53)
  at triggerExitCallback (C:\Users\90618\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\90618\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-erlang, v1.1.1
language-erlang, v3.0.0

# Dev
No dev packages
```

**Comment by wende** [comment]
1. You need to have autocomplete-plus package installed
2. Is elixir installed and in Your system PATH?
3. Is erlang installed and in Your system PATH ?
