### ISSUE TITLE
Uncaught Error: spawn E2BIG

### ISSUE THREAD

**Issue by ReuvenSwirsky** [iraasta/autocomplete-erlang#18]
_This happens when Atom starts. Feel free to contact me if you need more info. I'm brand new to Atom, so I don't have any experience debugging things._

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [autocomplete-erlang](https://github.com/iraasta/autocomplete-erlang) package, v1.1.1
### Stack Trace

Uncaught Error: spawn E2BIG

```
At /Users/swirsky/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn E2BIG
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Users/swirsky/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Users/swirsky/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at Object.exports.init (/Users/swirsky/.atom/packages/autocomplete-erlang/lib/alchemide/wrapper.coffee:29:14)
    at exit (/Users/swirsky/.atom/packages/autocomplete-erlang/lib/alchemide/wrapper.coffee:21:53)
    at triggerExitCallback (/Users/swirsky/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Users/swirsky/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
     -1:13.4.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "autocomplete-erlang": {
    "elixirPath": "/usr/local/bin/elixir"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-erlang, v1.1.1
language-erlang, v3.0.0

# Dev
No dev packages
```

**Comment by ReuvenSwirsky** [comment]
Have a workaround! Start atom from a terminal shell, not by clicking on it in Applications. Don't know what apple screwed up....
