### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdout' of undefined

### ISSUE THREAD

**Issue by swamibluedata** [iraasta/autocomplete-erlang#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-erlang](https://github.com/iraasta/autocomplete-erlang) package, v1.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'stdout' of undefined

```
At /Users/swamiv/.atom/packages/autocomplete-erlang/lib/alchemide/wrapper.coffee:34

TypeError: Cannot read property 'stdout' of undefined
  at Object.exports.init (/Users/swamiv/.atom/packages/autocomplete-erlang/lib/alchemide/wrapper.coffee:34:19)
  at exit (/Users/swamiv/.atom/packages/autocomplete-erlang/lib/alchemide/wrapper.coffee:21:53)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -0:54.7.0 core:close (atom-text-editor.editor.emacs-plus.is-focused)
     -0:45.3.0 core:move-right (atom-text-editor.editor.emacs-plus.is-focused)
     -0:45 core:move-down (atom-text-editor.editor.emacs-plus.is-focused)
     -0:44.9.0 core:move-left (atom-text-editor.editor.emacs-plus.is-focused)
     -0:44.7.0 editor:newline (atom-text-editor.editor.emacs-plus.is-focused)
     -0:42.8.0 emacs-plus:set-mark (atom-text-editor.editor.emacs-plus.is-focused)
     -0:41.5.0 emacs-plus:just-one-space (atom-text-editor.editor.emacs-plus.is-focused.mark-mode)
     -0:40.8.0 core:backspace (atom-text-editor.editor.emacs-plus.is-focused)
     -0:40.4.0 emacs-plus:just-one-space (atom-text-editor.editor.emacs-plus.is-focused)
  6x -0:40 core:backspace (atom-text-editor.editor.emacs-plus.is-focused)
     -0:38.5.0 core:move-right (atom-text-editor.editor.emacs-plus.is-focused)
     -0:38.2.0 core:move-up (atom-text-editor.editor.emacs-plus.is-focused)
     -0:38 core:select-down (atom-text-editor.editor.emacs-plus.is-focused)
     -0:37.6.0 core:backspace (atom-text-editor.editor.emacs-plus.is-focused.mark-mode)
     -0:37 core:save (atom-text-editor.editor.emacs-plus.is-focused)
     -0:34.8.0 core:close (atom-text-editor.editor.emacs-plus.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "autocomplete-erlang": {
    "elixirPath": "/usr/local/bin/elixir"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-erlang, v1.1.1
autocomplete-python, v0.5.1
emacs-plus, v0.9.5
language-erlang, v3.0.0

# Dev
No dev packages
```

**Comment by wende** [comment]
OSX is doing it's best to make atom crash. I'm trying to resolve this issues. It works perfectly fine from the commandline, but It doesn't want to work from finder

**Comment by tumbudu** [comment]
same is observed on Windows 10 too..

**Comment by hsaid** [comment]
Same on Windows 8, any updates coming soon? thanks

**Comment by wende** [comment]
As far as I'm concerned this is an issue with Atom itself. Or maybe some kind of security measure. I've got no idea nor even a lead where to look to make it access elixir executable. Embedding the whole thing is not a solution and it just doesn't let it acces a file in system user binaries

**Comment by hsaid** [comment]
Actually,I believe I fixed it. I inspected the Elixir script for autocompleter and noticed slight difference in function parameter. Then copied the file verbatim to Erlang autocompleter  and replaced it. It worked. I haven't done full test on it, but so far I am able to get Erlang code to autocomplete. The Elixir plugin works like a charm. BTW, while investigating this issue, got all fired up about Elixir, so bought a book and doing further  tests on your code.

**Comment by weiofcn** [comment]
@hsaid hi, genius, how's tests going, we can't wait for your update the fix. thanks.
