### ISSUE TITLE
Uncaught Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by emcek** [iraasta/autocomplete-erlang#7]
**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [autocomplete-erlang](https://github.com/iraasta/autocomplete-erlang) package, v1.1.1
### Stack Trace

Uncaught Error: spawn ENAMETOOLONG

```
At C:\Users\gtqk84\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:260

Error: spawn ENAMETOOLONG
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (C:\Users\gtqk84\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:188:44)
  at new BufferedProcess (C:\Users\gtqk84\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:50:14)
  at Object.exports.init (C:\Users\gtqk84\.atom\packages\autocomplete-erlang\lib\alchemide\wrapper.coffee:29:14)
  at exit (C:\Users\gtqk84\.atom\packages\autocomplete-erlang\lib\alchemide\wrapper.coffee:21:53)
  at triggerExitCallback (C:\Users\gtqk84\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\gtqk84\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "color-picker",
      "web-browser",
      "web-view",
      "package-generator",
      "language-toml",
      "language-sql",
      "language-sass",
      "language-ruby-on-rails",
      "language-ruby",
      "language-php",
      "language-objective-c",
      "language-mustache",
      "language-make",
      "language-java",
      "language-go",
      "language-clojure",
      "language-c",
      "background-tips",
      "exception-reporting",
      "language-csharp",
      "release-notes",
      "linter-less",
      "language-haskell",
      "welcome",
      "autocomplete-haskell",
      "haskell-grammar",
      "helium",
      "ide-haskell",
      "SFTP-deployment",
      "compare-files"
    ],
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "autocomplete-erlang": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, vundefined
autoclose-html, v0.18.0
autocomplete-erlang, v1.1.1
autocomplete-paths, v1.0.2
command-logger, v0.23.0
editor-stats, v0.17.0
file-icons, v1.5.8
git-log, v0.4.1
git-tab-status, v1.9.2
haskell-ghc-mod, v0.8.0
language-diff, v0.3.0
language-erlang, v3.0.0
language-lua, v0.9.4
language-robot-framework, v0.9.0
linter, v1.1.0
linter-csslint, v0.0.14
linter-erlc, v0.3.0
linter-flake8, v1.4.2
linter-hlint, v0.3.6
linter-htmlhint, v0.0.16
linter-lua, v0.1.6
linter-luacheck, v0.5.0
linter-pep8, v0.2.0
linter-pyflakes, v0.0.5
linter-pylama, vundefined
linter-pylint, v0.2.2
linter-shellcheck, v0.0.8
linter-tidy, v1.0.1
minimap, v4.10.1
project-manager, v1.15.10
travis-ci-status, v0.15.1

# Dev
No dev packages
```

**Comment by wende** [comment]
This is Node.js error. You can't pass too long paths to process spawning because then it goes bananas. I can't help with it.
Copying Your project files to some less nested directory will fix the thing.

**Comment by emcek** [comment]
I see.
